### PR TITLE
Strange, build dll failed, visual studio bug?

### PR DESCRIPTION
**Pull request by halx99**
Static lib works, dynamic doesn't, caused by new custom spritesheet loader:
```cpp
std::map<uint32_t, std::uniqie_ptr<ISpriteSheetLoader>> loaders;
```

### CODE REVIEW

**Comment by halx99** [comment]
@rh101 Could you take a look about this issue, the error caused by: https://github.com/adxeproject/adxe/blob/dev/cocos/2d/CCSpriteFrameCache.h#L291
And when I change it to ```std::map<uint32_t, std::shared_ptr<ISpriteSheetLoader>>```, works.

**Comment by halx99** [comment]
Some other reference: https://www.py4u.net/discuss/89823

**Comment by rh101** [comment]
Sorry, I didn't notice this issue earlier.  Yeah I get why `unique_ptr` is not working with a dynamic library, and there is no reason we can't use `shared_ptr` instead.

**Comment by rh101** [comment]
Fix is in #471

**Pull request closed without merging**
