### PR TITLE
[IMPROVMENT] Change class name `Sprite3D` to `MeshRenderer`

### PR DESCRIPTION
**Pull request by DelinWorks**
Refer to #688

### CODE REVIEW

**Comment by aismann** [comment]
We should generate a list of rename function, classes, etc
<old>  <new>
...

**Comment by DelinWorks** [comment]
Good catch! I'll add it in this PR along with `Director` functions that were changed.

**Comment by DelinWorks** [comment]
Okay @halx99 I'm done with my commits.

**Review by halx99 — APPROVED** [review]

**Comment by aismann** [comment]
Maybe a list of new functions, classes, etc is also helpfull?
and add it to a doc like 'NEW_API.md'
Can be  a seperate build of course

**Comment by DelinWorks** [comment]
> Maybe a list of new functions, classes, etc is also helpfull? and add it to a doc like 'NEW_API.md' Can be a seperate build of course

that's actually handled in `CHANGELOG.md` in the root directory of the repo

**Comment by aismann** [comment]
> > Maybe a list of new functions, classes, etc is also helpfull? and add it to a doc like 'NEW_API.md' Can be a seperate build of course
> 
> that's actually handled in `CHANGELOG` file in the root directory of the repo

The new: 'enum AnchorPreset' will be found there?

**Comment by halx99** [comment]
Merge first

**Pull request merged**
