### PR TITLE
 Global NumPadPosType can be used for all situations where to set the position on object like the numbers on the numpad

### PR DESCRIPTION
**Pull request by aismann**

### CODE REVIEW

**Comment by aismann** [comment]
see also #699

**Comment by DelinWorks** [comment]
Wait so you want to create `ccEnums.h`?

**Comment by DelinWorks** [comment]
Maybe rename the `NumPadPosType` enum to `PositionAnchor` more comprehensible.

**Comment by aismann** [comment]
> Wait so you want to create `ccEnums.h`?

Im  in a hurrry. would only add the changes because it would be reduce the work.
But if it should be rename again so the  pr can be deleted and you start it with new.

**Comment by DelinWorks** [comment]
yeah delete the PR i'll do it

**Comment by aismann** [comment]
> yeah close the PR i'll do it

Thanks.

**Pull request closed without merging**
