### PR TITLE
Update CCConsole.cpp

### PR DESCRIPTION
**Pull request by aismann**
log only  if COCOS2D_DEBUG != 0

### CODE REVIEW

**Comment by halx99** [comment]
If I want log message in release mode, how?

**Comment by aismann** [comment]
> 



> If I want log message in release mode, how?

set COCO2D_DEBUG=1 (hardcoded on your 'want to test code')
another idea:
Add some new log types like:
ADXE_TRACE
ADXE_WARNING
ADXE_ERROR
ADXE_LOG   (always log also on release version)

**Comment by aismann** [comment]
Once more:
log(...) should used on release mode "ONLY" if there is an issue and rermove it when 'fixed'.
Cocos2dx has used it to much also on release mode without removing it again (I think).

**Comment by halx99** [comment]
Log level:
- TRACE/DEBUG
- INFO
- WARN
- ERROR

**Comment by aismann** [comment]
I remove this PR and will add a better one

**Pull request closed without merging**
