### PR TITLE
Fix Label issue #565

### PR DESCRIPTION
**Pull request by DelinWorks**
- Refer to: #565 
- Relative PR: #566

### CODE REVIEW

**Comment by halx99** [comment]
Maybe we can rename `scaleFontSizeDown` to `scaleFontSize` as @rh101  said.

**Comment by DelinWorks** [comment]
Yeah why not, I'll do it
But can i make commits that will apply to this PR?

**Comment by rh101** [comment]
> Yeah why not, I'll do it But can i make commits that will apply to this PR?

Make your change locally, then push them to the same branch, "label-issue-566" in your case, and it'll automatically update this PR.

**Comment by DelinWorks** [comment]
Don't worry I wont jinx it this time xD

**Comment by rh101** [comment]
@DelinWorks Please avoid committing small changes like that. Do all the changes locally, then commit them all at once.

**Comment by DelinWorks** [comment]
Oh okay

**Comment by DelinWorks** [comment]
I made the same changes in my machine and I'm currently compiling it seeing if there is any errors

**Comment by rh101** [comment]
> I made the same changes in my machine and I'm currently compiling it seeing if there is any errors

Also, don't push changes until after you've tested them.  You're fine to commit them to your local branch, just don't push them until you know they work.

**Comment by DelinWorks** [comment]
Okay, I made the mistake of not using github desktop.. i should edit files and commit them all at once

**Comment by DelinWorks** [comment]
It compiled! les goo

**Comment by rh101** [comment]
> Okay, I made the mistake of not using github desktop.. i should edit files and commit them all at once

I don't understand? I don't use github desktop, just command line or TortoiseGit, and then run the code in Visual Studio, which can also commit and push changes with the built in git tools.

**Comment by DelinWorks** [comment]
What I meant is pulling the project files in your machine and then by some program like (Github Desktop, CLI or TortoiseGit) commiting them when done. Me i didnt i just edited every file in the web interface

**Comment by rh101** [comment]
> Me i didnt i just edited every file in the web interface

Oh, yep, I now understand what you mean. The web interface is probably more suitable for very simply changes that don't require recompilation or testing etc.

**Comment by DelinWorks** [comment]
So now it's working I've compiled it.. do we wait?

**Comment by rh101** [comment]
> So now it's working I've compiled it.. do we wait?

Yes. Once the checks have passed, and assuming there are no issues, it needs to get approved and merged in by @halx99 

For the time being, you've got the changes locally, so you can just continue on with your project.  Once the PR is merged in, you can then update your fork, and sync with your local again.

**Review by halx99 — APPROVED** [review]

**Comment by DelinWorks** [comment]
Cool! what a learning experience lol
Thank you guys for being patient with me xD

**Comment by rh101** [comment]
> just did a quick lil regex search

You don't need to list the files you changed, since we can already see exactly what has changed: 
image

**Comment by halx99** [comment]
Merged, thanks

**Pull request merged**
