### PR TITLE
Improve Chipmunk2D -TestBed and DebugDraw too

### PR DESCRIPTION
**Pull request by aismann**

### CODE REVIEW

**Comment by halx99** [comment]
Please resolve confilicts

**Comment by aismann** [comment]
I have no rights.

**Comment by aismann** [comment]
How can I resolve it?

**Comment by halx99** [comment]
> How can I resolve it?

I have resolved, please review the changes

**Review by aismann — COMMENTED** [review]
should be ok.

**Comment by halx99** [comment]
Thanks

**Pull request merged**
