### PR TITLE
Update controller.cpp

### PR DESCRIPTION
**Pull request by aismann**

### CODE REVIEW

**Comment by aismann** [comment]
Can you have a look on the error?

**Comment by halx99** [comment]
> Can you have a look on the error?

The file `Box2DTestBedTests.cpp` not in CMakeLists.txt

**Comment by halx99** [comment]
You should remove the windows conditon check from `CMakeLists.txt`: https://github.com/aismann/adxe/blob/dev/tests/cpp-tests/CMakeLists.txt#L376

**Comment by aismann** [comment]
I have no idea what is wrong... error message is clear but test.h is correct, isnt it?

**Comment by halx99** [comment]
> I have no idea what is wrong... error message is clear but test.h is correct, isnt it?

Your branch the test.h is start with uppercase `T` `Test.h`, but at CMakeLists.txt, you use lowercase

**Comment by halx99** [comment]
Please rename follow files at the `CMakeLists.txt`
- `Classes/Box2DTestBed/test.h` --> `Classes/Box2DTestBed/Test.h`
- `Classes/Box2DTestBed/test.cpp` --> `Classes/Box2DTestBed/Test.cpp`

**Comment by aismann** [comment]
Very interesting, the files on windows be lowercase (test.h test.cpp) and this is be correct.

I want use the original "testbed demo files) and there is ../test.h  incuded...thats the reason for lower case!!!

**Comment by halx99** [comment]
The windows is case-insensitive, sometimes the windows explorer display maybe incorrect

**Comment by aismann** [comment]
But lowercase is the correct one for use the origanal files as possible

**Comment by halx99** [comment]
> But lowercase is the correct one for use the origanal files as possible

You can change to lowercase on github web page or on a linux machine

**Comment by aismann** [comment]
Can you made it plz?
I have no linux and didnet use github web anytime

**Comment by halx99** [comment]
ok, I will

**Comment by halx99** [comment]
I will merge this pr first

**Comment by aismann** [comment]
Thanks. please start the buildprocess again after it

**Comment by halx99** [comment]
Done: https://github.com/adxeproject/adxe/pull/424

**Pull request merged**
